pass info channel url to gh action docker build

diff --git a/docker/Dockerfile.prod b/docker/Dockerfile.prod
--- a/docker/Dockerfile.prod
+++ b/docker/Dockerfile.prod
@@ -36,15 +36,22 @@ ENV NEXT_TELEMETRY_DISABLED 1
 # Pass the name of the Telegram bot from GitHub variables to the build process if it exists.
 # This is required because the bot name is statically rendered for the Telegram login button.
 RUN --mount=type=secret,id=NEXT_PUBLIC_TG_BOT_NAME \
- if [ -f "/run/secrets/NEXT_PUBLIC_TG_BOT_NAME" ]; then \
-  export NEXT_PUBLIC_TG_BOT_NAME=$(cat /run/secrets/NEXT_PUBLIC_TG_BOT_NAME); \
- fi && \
- if [ -f pnpm-lock.yaml ]; \
- then \
-   SKIP_ENV_VALIDATION=1 pnpm run build; \ 
- else \
-  echo "Lockfile not found." && exit 1; \
- fi
+    --mount=type=secret,id=NEXT_PUBLIC_TG_INFO_CHANNEL \
+    if [ -f "/run/secrets/NEXT_PUBLIC_TG_BOT_NAME" ]; then \
+      export NEXT_PUBLIC_TG_BOT_NAME=$(cat /run/secrets/NEXT_PUBLIC_TG_BOT_NAME); \
+    else \
+      echo "Secret NEXT_PUBLIC_TG_BOT_NAME not found."; \
+    fi && \
+    if [ -f "/run/secrets/NEXT_PUBLIC_TG_INFO_CHANNEL" ]; then \
+      export NEXT_PUBLIC_TG_INFO_CHANNEL=$(cat /run/secrets/NEXT_PUBLIC_TG_INFO_CHANNEL); \
+    else \
+      echo "Secret NEXT_PUBLIC_TG_INFO_CHANNEL not found."; \
+    fi && \
+    if [ -f pnpm-lock.yaml ]; then \
+      SKIP_ENV_VALIDATION=1 pnpm run build; \
+    else \
+      echo "Lockfile not found." && exit 1; \
+    fi
 
 ##### RUNNER
 
